name: Auto Synchronization

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Change permission
      run: |
        chmod +x ./auto_sync.sh

    - name: Run
      run: |
        ./auto_sync.sh "$TOKEN"
      shell: bash
      env:
        TOKEN: ${{ secrets.PERSONAL_TOKEN }}
